### ISSUE TITLE
USER STORY (#2) : Project Setup

### ISSUE THREAD

**Issue by yamesjamess** [yamesjamess/p5-feast-your-eyes-drf-api#14]
As a **developer** I can **use all the info from the requirement to set up a repo** so that **I can start develop to API model and the front end**

Acceptance Criteria

1. Given that I am a developer I will setup the repo to connect to Cloudinary
2. Given that I am a developer I will setup the dev db to use sqlite3 and ElephantSQL for the production database
3. Given that I am a developer I will setup secret keys in env.py and add to git.ignore

- [x] Setup using CI DRF Cheat Sheet https://docs.google.com/document/d/1LCLxWhmW_4VTE4GXsnHgmPUwSPKNT4KyMxSH8agbVqU/edit#heading=h.mpopj7v69qqn
- [x] Update settings.py
- [x]  Create ElephantSQL database
- [x]  Create cloudinary link
- [x]  Create Secret Keys
- [x]  Create env.py and git.ignore
