### ISSUE TITLE
USER STORY (#3) : Profiles Model

### ISSUE THREAD

**Issue by yamesjamess** [yamesjamess/p5-feast-your-eyes-drf-api#15]
As a **admin** I can **login to the admin panel** so that **I can manage user profiles**

Acceptance Criteria

1. Given that I am a superuser, I can log in to the admin area of django
2. Given that I am a superuser, I can create, edit and delete other users
3. Given that I am a superuser, I can create, edit and delete name, bio and image fields on my profile

- [x] Create Profile model with name, bio and image field linked to cloudinary
- [x]  Create urls.py
- [x]  Register admin.py
- [x]  Create Serializers
- [x]  Use django signals to trigger a post_savefunction to create a profile
- [x]  Create views.py
- [x]  Ensure there is a default image that is displayed when a user has not uploaded a picture
- [x]  Login and check profile with default image
- [x]  Create additional profile with own image
