### ISSUE TITLE
USER STORY (#38) :  Documentation

### ISSUE THREAD

**Issue by yamesjamess** [yamesjamess/p5-feast-your-eyes-drf-api#79]
As a **developer** I can **write a comprehensive documentation** so that **other developer can read the README.md and understand my project**

Acceptance Criteria

- [x] UX
- [x] Features
- [x] Existing Features
- [ ] How these features support the user stories
- [x] Feature that could be implemented in the future
- [x] Design
- [x] Wireframe
- [x] Entity-Relationship for the Database
- [x] Planning
- [x] Technologies Used
- [x] Languages Used
- [x] Frameworks, Libraries & Programs Used
- [x] Testing
- [x] Validator Testing
- [x] Automated Testing
- [x] Browser Compatibility
- [ ] Test Cases and Results
- [x] Known Bugs
- [x] Unfixed Bugs
- [x] Deployment
- [x] How to clone this repository
- [x] How to deploy the program on Heroku
- [x] Credits
- [x] Code
- [x] Content
- [x] Media
- [x] Acknowledgements

**Comment by yamesjamess** [comment]
eslint credits
https://stackoverflow.com/questions/72780296/warning-react-version-not-specified-in-eslint-plugin-react-settings-while-run
https://stackoverflow.com/questions/49789177/module-is-not-defined-and-process-is-not-defined-in-eslint-in-visual-studio-code
https://stackoverflow.com/questions/42541559/eslint-with-react-gives-no-unused-vars-errors
https://stackoverflow.com/questions/56398742/eslint-throws-no-undef-errors-when-linting-jest-test-files
https://stackoverflow.com/questions/62031536/referenceerror-test-is-not-defined-with-jest
https://stackoverflow.com/questions/52992932/component-definition-is-missing-display-name-react-display-name
https://github.com/AtomLinter/linter-eslint/issues/462
